services:
  - type: web
    name: prompt-extractor
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 5001
      - key: PROMPT_EXTRACTOR_APP_DIR
        value: /tmp/prompt-extractor-app
      - key: PROMPT_EXTRACTOR_OUTPUT_DIR
        value: /tmp/prompt-extractor-data
